In [3]:
import OOP_way_try as op
import numpy as np
from scipy import signal
import json

In [40]:
def matrix_from_fen(fen:str)->np.ndarray:
    matrix_board = np.zeros((6,8,8))
    board_str = fen.split(" ")[0]
    board_str = board_str.replace("1", ".")
    board_str = board_str.replace("2", "..")
    board_str = board_str.replace("3", "...")
    board_str = board_str.replace("4", "....")
    board_str = board_str.replace("5", ".....")
    board_str = board_str.replace("6", "......")
    board_str = board_str.replace("7", ".......")
    board_str = board_str.replace("8", "........")
    board_list = board_str.split("/")
    board_mtr_str = np.array([list(rank) for rank in board_list])
    pawns = (board_mtr_str == "P").astype(float)-(board_mtr_str == "p").astype(float)
    rooks = (board_mtr_str == "R").astype(float)-(board_mtr_str == "r").astype(float)
    knights = (board_mtr_str == "N").astype(float)-(board_mtr_str == "n").astype(float)
    bishops = (board_mtr_str == "B").astype(float)-(board_mtr_str == "b").astype(float)
    queens = (board_mtr_str == "Q").astype(float)-(board_mtr_str == "q").astype(float)
    kings = (board_mtr_str == "K").astype(float)-(board_mtr_str == "k").astype(float)
    
    matrix = np.array([pawns, rooks, knights, bishops, queens, kings])
    return matrix

In [ ]:
json_file = "/Users/robin/Downloads/lichess_db_eval.jsonl"
with open(json_file, "r") as pej:
    positions = json.load(pej)

print(positions[0])

In [41]:
fen = "rnbqkbnr/pp1ppppp/8/2p5/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2"

matrix_rep = matrix_from_fen(fen)
for matrix in matrix_rep:
    print(matrix)
# game_state = op.Game_state()
# game_state.set_game_state_from_fen(fen)

[[ 0  0  0  0  0  0  0  0]
 [-1 -1  0 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 1  1  1  1  0  1  1  1]
 [ 0  0  0  0  0  0  0  0]]
[[-1  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  1]]
[[ 0 -1  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0]]
[[ 0  0 -1  0  0 -1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  1  0  0]]
[[ 0  0  0 -1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  

In [ ]:
def sigmoid(x):
    new_array = 1/(1+np.exp(-x))
    return new_array

def deri_sigm(x):
    new_array = 1/(1+np.exp(-x)+np.exp(x))
    return new_array


In [ ]:
def forward_pass(matrix, weights: dict)-> float &float:
    w1=weights["w1"]
    b1=weights["b1"]
    w2=weights["w2"]
    b2=weights["b2"]
    
    a1 = np.copy(b1)
    for i in range(6):
        a1 += signal.convolve2d(matrix,w1,mode="valid")
    na1 = sigmoid(a1)
    a2 = np.copy(b2) + np.dot(na1,w2)
    na2 = sigmoid(a2)
    predicted_eval = np.sum(na2)
    
    diff = {"da2": np.dot(deri_sigm(a2))}
    
    
    
    return predicted_eval, diff